from pathlib import Path

music_path = Path('src/features/music/MusicScreens.tsx')
music = music_path.read_text()
# Unknown means Desk is resolving whether a durable read exists. Do not expose generation until that state is known.
music = music.replace('  const failed = song.managerReadStatus === "failed" || song.managerReadStatus === "refresh_failed" || Boolean(briefError);\n', '  const failed = song.managerReadStatus === "failed" || song.managerReadStatus === "refresh_failed" || Boolean(briefError);\n  const checking = song.managerReadStatus === "unknown";\n', 1)
music = music.replace('Couldn\'t refresh just now. Showing the last read.', 'Couldn’t refresh just now. Showing the last read.')
needle = '''      ) : readBusy ? (\n        <div className="mt-4 flex max-w-xl items-center gap-3 py-2">\n          <AppThinkingOrb surface="normal" state="composing" size={20} />\n          <p className="text-[13px] font-semibold text-muted-foreground">Manager is reading this record…</p>\n        </div>\n      ) : ('''
replacement = '''      ) : readBusy ? (\n        <div className="mt-4 flex max-w-xl items-center gap-3 py-2">\n          <AppThinkingOrb surface="normal" state="composing" size={20} />\n          <p className="text-[13px] font-semibold text-muted-foreground">Manager is reading this record…</p>\n        </div>\n      ) : checking ? (\n        <div className="mt-4 max-w-xl">\n          <p className="text-[13px] font-semibold text-muted-foreground">Checking Manager’s read…</p>\n          <button type="button" onClick={onGenerateBrief} className="mt-3 inline-flex min-h-8 items-center gap-1.5 text-[11px] font-semibold text-muted-foreground transition-colors hover:text-foreground focus:outline-none focus:ring-2 focus:ring-brand-accent/25">\n            <RefreshCw className="h-3.5 w-3.5" aria-hidden="true" /> Check again\n          </button>\n        </div>\n      ) : ('''
if needle not in music:
    raise SystemExit('song read branching anchor missing')
music = music.replace(needle, replacement, 1)
music_path.write_text(music)

shell_path = Path('src/production-app-shell.test.tsx')
shell = shell_path.read_text()
# Existing catalog-room assertions now reflect the intentionally reduced Overview.
shell = shell.replace('    expect(songRoom).toHaveTextContent("Confirm split sheet");', '    expect(songRoom).toHaveTextContent("Night Bus has the strongest aligned response");\n    expect(songRoom).toHaveTextContent("Release Night Bus on June 12");')
shell = shell.replace('    expect(mobileSongTitle.nextElementSibling).toBeNull();', '    expect(within(mobileSongTop).getByRole("button", { name: "Chat with Manager" })).toBeInTheDocument();')
shell = shell.replace('    expect(within(songRoom).getByTestId("song-room-mobile-tabs")).toHaveClass("grid-cols-5");', '    expect(within(songRoom).getByTestId("song-room-mobile-tabs")).toHaveClass("grid-cols-4");')
shell = shell.replace('    expect(within(songRoom).getByTestId("song-room-mobile-overview")).toHaveClass("rounded-[16px]");\n    expect(within(songRoom).getByTestId("song-room-mobile-overview")).not.toHaveClass("rounded-[22px]");', '    expect(within(songRoom).getByTestId("song-room-mobile-overview")).not.toHaveClass("rounded-[16px]");\n    expect(within(songRoom).getByTestId("song-room-mobile-overview")).not.toHaveClass("rounded-[22px]");')
shell = shell.replace('    expect(within(songRoom).getByRole("region", { name: "Work on this song" })).toBeInTheDocument();', '    expect(within(songRoom).getByRole("region", { name: "Active work" })).toBeInTheDocument();')
# Focused Song Room owns the mobile viewport; the global nav must be absent until the user backs out.
shell = shell.replace('    expect(screen.getByTestId("mobile-tabbar")).toBeInTheDocument();\n    expect(scrollTo).toHaveBeenLastCalledWith({ top: 0, left: 0, behavior: "auto" });\n\n    fireEvent.click(screen.getByTestId("mobile-tab-Catalog"));\n    expect(screen.getByTestId("music-mobile-library")).toBeInTheDocument();\n    expect(screen.getByTestId("mobile-app-topbar")).toBeInTheDocument();', '    expect(screen.queryByTestId("mobile-tabbar")).not.toBeInTheDocument();\n    expect(scrollTo).toHaveBeenLastCalledWith({ top: 0, left: 0, behavior: "auto" });\n\n    fireEvent.click(screen.getByRole("button", { name: "Back to Catalog from mobile room" }));\n    expect(screen.getByTestId("music-mobile-library")).toBeInTheDocument();\n    expect(screen.getByTestId("mobile-app-topbar")).toBeInTheDocument();')
# Recipient-first Share no longer exposes file checkboxes on the entry screen.
shell = shell.replace('''    expect(screen.getByRole("dialog", { name: "Share Jam files" })).toBeInTheDocument();\n    expect(screen.getByLabelText("Final master")).toBeChecked();\n    fireEvent.click(await screen.findByRole("button", { name: "Manage links" }));''', '''    expect(screen.getByRole("dialog", { name: "Share Jam" })).toBeInTheDocument();\n    fireEvent.click(await screen.findByRole("button", { name: "Links" }));''')
shell = shell.replace('''    fireEvent.click(within(room).getByRole("button", { name: "Share files" }));\n    fireEvent.click(screen.getByRole("button", { name: "Create link" }));\n    expect(await screen.findByRole("heading", { name: "Link ready" })).toBeInTheDocument();''', '''    fireEvent.click(within(room).getByRole("button", { name: "Share files" }));\n    fireEvent.click(await screen.findByRole("button", { name: /A&R \/ private listen/i }));\n    fireEvent.click(screen.getByRole("button", { name: "Preview private listen" }));\n    fireEvent.click(await screen.findByRole("button", { name: "Create private link" }));\n    expect(await screen.findByRole("heading", { name: "Share link ready" })).toBeInTheDocument();''')
shell = shell.replace('    fireEvent.click(screen.getByRole("button", { name: "Revoke link" }));', '    fireEvent.click(screen.getByRole("button", { name: "Revoke" }));')
shell = shell.replace('    expect(screen.getByText("This package is no longer accessible.")).toBeInTheDocument();', '    expect(screen.getByText("This package can no longer be opened.")).toBeInTheDocument();')
# Minimal Manager Read vocabulary replaces the old system-state copy.
shell = shell.replace('getByRole("button", { name: "Ask Manager for a read" })', 'getByRole("button", { name: "Get Manager’s read" })')
shell = shell.replace('    expect(screen.getByTestId("music-song-detail")).toHaveTextContent("Not generated");', '    expect(screen.getByTestId("music-song-detail")).toHaveTextContent("Get Manager’s take on this record.");')
shell = shell.replace('    expect(await within(room).findByText("Manager Read could not start. Try again.")).toBeInTheDocument();', '    expect(await within(room).findByText("Manager couldn’t complete the read.")).toBeInTheDocument();')
shell = shell.replace('    expect(screen.getByTestId("music-song-detail")).toHaveTextContent("No Manager Read yet");\n    expect(within(screen.getByTestId("music-song-detail")).getByRole("button", { name: "Check status" })).toBeInTheDocument();', '    expect(screen.getByTestId("music-song-detail")).toHaveTextContent("Get Manager’s take on this record.");\n    expect(within(screen.getByTestId("music-song-detail")).getByRole("button", { name: "Get Manager’s read" })).toBeInTheDocument();')
shell = shell.replace('    expect(room).toHaveTextContent("Status available when opened");\n    expect(within(room).getByRole("button", { name: "Check status" })).toBeInTheDocument();\n    expect(within(room).queryByRole("button", { name: "Ask Manager for a read" })).not.toBeInTheDocument();', '    expect(room).toHaveTextContent("Checking Manager’s read");\n    expect(within(room).getByRole("button", { name: "Check again" })).toBeInTheDocument();\n    expect(within(room).queryByRole("button", { name: "Get Manager’s read" })).not.toBeInTheDocument();')
# Typography uses the product's curly apostrophe.
shell = shell.replace('Couldn\'t refresh just now. Showing the last read.', 'Couldn’t refresh just now. Showing the last read.')
shell_path.write_text(shell)
